swagger: '2.0'
info:
  version: 1.0.0
  title: Budget API
  description: |
    REST API service for providing/storing budget data by request
schemes:
- http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
paths:
  /spendings:
    get:
      summary: Get a list of spendings
      description: ""
      tags:
      - Spendings
      parameters:
      - name: category
        in: query
        description: budget category
        type: string
        required: false
        enum:
        - entertainment
        - car
        - bill
        - food
        - home
        - education
        - other
      - name: label
        in: query
        description: label
        type: string
        required: false
      - name: start
        in: query
        description: date the start of period
        type: string
        required: false
      - name: end
        in: query
        description: date the end of period
        type: string
        required: false
      - name: page
        in: query
        description: page number
        type: integer
        required: true
      - name: perPage
        in: query
        description: results per page
        type: integer
        required: true
      - name: sortBy
        in: query
        description: sort result by this field
        type: string
        required: false
      - name: sortOrder
        in: query
        description: sort order
        type: string
        enum: [asc, desc]
        required: fasle
      security:
      - x_auth: []
      responses:
        '200':
          description: successful request
        '405':
          description: Not allowed - Method is not allowed on the current resource
        '500':
          description: Internal Error - Internal server error
        default:
          description: Unexpected error
    post:
      summary: Save one spending
      description: ""
      parameters:
      - name: category
        in: body
        description: budget category
        type: string
        required: true
        enum:
        - entertainment
        - car
        - bill
        - food
        - home
        - education
        - other
      - name: createdOn
        in: body
        description: date of spending
        type: string
        required: true
      - name: label
        in: body
        description: labels
        type: string
        required: false
      - name: amount
        in: body
        description: amount
        type: string
        required: true
      security:
      - x_auth: []
  '/spendings/{id}':
    get:
      summary: Get one spending
      description: ""
      tags:
      - Spending
      parameters:
      - name: id
        in: path
        description: id of spending item
        required: true
        type: string
      security:
      - x_auth: []
    patch:
      summary: Update one spending
      description: ""
      parameters:
      - name: id
        in: path
        description: id of spending item
        required: true
        type: string
      - name: category
        in: body
        description: budget category
        type: string
        required: false
        enum:
        - entertainment
        - car
        - bill
        - food
        - home
        - education
        - other
      - name: createdOn
        in: body
        description: date of spending
        type: string
        required: false
      - name: label
        in: body
        description: label
        type: string
        required: false
      - name: amount
        in: body
        description: amount
        type: string
        required: false
      security:
      - x_auth: []
    delete:
      summary: Delete one spending
      description: ""
      parameters:
      - name: id
        in: path
        description: id of spending item
        required: true
        type: string
      security:
      - x_auth: []
definitions:
  Spending:
    type: object
    properties:
      id:
        type: string
      createdOn:
        type: string
      label:
        type: string
      category:
        type: string
        enum:
        - entertainment
        - car
        - bill
        - food
        - home
        - education
        - other

