const HTTP_STATUS_CODES = {
  OK: 200,
  BAD_REQUEST: 400,
  INTERNAL_SERVER_ERROR: 500
}

const CURRENCY = {
  USD: 2.43,
  RUB: 0.035,
  EUR: 2.8
}

module.exports = { HTTP_STATUS_CODES, CURRENCY }
